name: QA Portal Services

on:
  push:
    branches:
      - "feature/**"

jobs:
  build:
    runs-on: ubuntu-18.04

    services:
      postgres:
        image: ianowenqa/qa-portal-postgres-test-db
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        working-directory: ./qa-portal-services
        run: mvn clean install
